export { default as CompletedIcon } from "./Icons/CompletedIcon.icon"
export { default as GithubIcon } from "./Icons/GithubIcon.icon"
export { default as HomeIcon } from "./Icons/HomeIcon.icon"
export { default as LinkedinIcon } from "./Icons/LinkedinIcon.icon"
export { default as PencilIcon } from "./Icons/PencilIcon.icon"
